// Daten aus dem Formular in JSON zusammenfassen
    function form_to_compressed_JSON() {
        var form_data = {
            date_saved: new Date().toISOString().split('T')[0],
            date: encodeURIComponent(document.forms[0]["date"].value.slice(0, 20)),
            url: "www.periodontalchart-online.com",
            copyright: "www.perio-tools.com (2024)",
            patient_last_name: encodeURIComponent(document.forms[0]["patient_last_name"].value.slice(0, 50)),
            patient_first_name: encodeURIComponent(document.forms[0]["patient_first_name"].value.slice(0, 50)),
            patient_dob: encodeURIComponent(document.forms[0]["patient_dob"].value.slice(0, 20)),
            initial_exam: initial_exam.toString(),
            reevaluation: reevaluation.toString(),
            input_reevaluation: encodeURIComponent(document.forms[0]["input_reevaluation"].value.slice(0, 100)),
            clinician: encodeURIComponent(document.forms[0]["clinician"].value.slice(0, 20)),
            tooth_18: tooth_18.toString(),
            mobility_18: encodeURIComponent(document.forms[0]["mobility_18"].value),
            furcation_18_b: Furkation_18_b.toString(),
            furcation_18_dp: Furkation_18_dp.toString(),
            furcation_18_mp: Furkation_18_mp.toString(),
            implant_18: Implantat_18.toString(),
            bop_18_db: bop_18_db.toString(),
            bop_18_b: bop_18_b.toString(),
            bop_18_mb: bop_18_mb.toString(),
            pi_18_db: pi_18_db.toString(),
            pi_18_b: pi_18_b.toString(),
            pi_18_mb: pi_18_mb.toString(),
            bop_18_dp: bop_18_dp.toString(),
            bop_18_p: bop_18_p.toString(),
            bop_18_mp: bop_18_mp.toString(),
            pi_18_dp: pi_18_dp.toString(),
            pi_18_p: pi_18_p.toString(),
            pi_18_mp: pi_18_mp.toString(),
            gm_18_db: encodeURIComponent(document.forms[0]["gm_18_db"].value),
            gm_18_b: encodeURIComponent(document.forms[0]["gm_18_b"].value),
            gm_18_mb: encodeURIComponent(document.forms[0]["gm_18_mb"].value),
            pd_18_db: encodeURIComponent(document.forms[0]["pd_18_db"].value),
            pd_18_b: encodeURIComponent(document.forms[0]["pd_18_b"].value),
            pd_18_mb: encodeURIComponent(document.forms[0]["pd_18_mb"].value),
            gm_18_dp: encodeURIComponent(document.forms[0]["gm_18_dp"].value),
            gm_18_p: encodeURIComponent(document.forms[0]["gm_18_p"].value),
            gm_18_mp: encodeURIComponent(document.forms[0]["gm_18_mp"].value),
            pd_18_dp: encodeURIComponent(document.forms[0]["pd_18_dp"].value),
            pd_18_p: encodeURIComponent(document.forms[0]["pd_18_p"].value),
            pd_18_mp: encodeURIComponent(document.forms[0]["pd_18_mp"].value),
            note_18: encodeURIComponent(document.forms[0]["note_18"].value.slice(0, 5)),

            tooth_17: tooth_17.toString(),
            mobility_17: encodeURIComponent(document.forms[0]["mobility_17"].value),
            furcation_17_b: Furkation_17_b.toString(),
            furcation_17_dp: Furkation_17_dp.toString(),
            furcation_17_mp: Furkation_17_mp.toString(),
            implant_17: Implantat_17.toString(),
            bop_17_db: bop_17_db.toString(),
            bop_17_b: bop_17_b.toString(),
            bop_17_mb: bop_17_mb.toString(),
            pi_17_db: pi_17_db.toString(),
            pi_17_b: pi_17_b.toString(),
            pi_17_mb: pi_17_mb.toString(),
            bop_17_dp: bop_17_dp.toString(),
            bop_17_p: bop_17_p.toString(),
            bop_17_mp: bop_17_mp.toString(),
            pi_17_dp: pi_17_dp.toString(),
            pi_17_p: pi_17_p.toString(),
            pi_17_mp: pi_17_mp.toString(),
            gm_17_db: encodeURIComponent(document.forms[0]["gm_17_db"].value),
            gm_17_b: encodeURIComponent(document.forms[0]["gm_17_b"].value),
            gm_17_mb: encodeURIComponent(document.forms[0]["gm_17_mb"].value),
            pd_17_db: encodeURIComponent(document.forms[0]["pd_17_db"].value),
            pd_17_b: encodeURIComponent(document.forms[0]["pd_17_b"].value),
            pd_17_mb: encodeURIComponent(document.forms[0]["pd_17_mb"].value),
            gm_17_dp: encodeURIComponent(document.forms[0]["gm_17_dp"].value),
            gm_17_p: encodeURIComponent(document.forms[0]["gm_17_p"].value),
            gm_17_mp: encodeURIComponent(document.forms[0]["gm_17_mp"].value),
            pd_17_dp: encodeURIComponent(document.forms[0]["pd_17_dp"].value),
            pd_17_p: encodeURIComponent(document.forms[0]["pd_17_p"].value),
            pd_17_mp: encodeURIComponent(document.forms[0]["pd_17_mp"].value),
            note_17: encodeURIComponent(document.forms[0]["note_17"].value.slice(0, 5)),

            tooth_16: tooth_16.toString(),
            mobility_16: encodeURIComponent(document.forms[0]["mobility_16"].value),
            furcation_16_b: Furkation_16_b.toString(),
            furcation_16_dp: Furkation_16_dp.toString(),
            furcation_16_mp: Furkation_16_mp.toString(),
            implant_16: Implantat_16.toString(),
            bop_16_db: bop_16_db.toString(),
            bop_16_b: bop_16_b.toString(),
            bop_16_mb: bop_16_mb.toString(),
            pi_16_db: pi_16_db.toString(),
            pi_16_b: pi_16_b.toString(),
            pi_16_mb: pi_16_mb.toString(),
            bop_16_dp: bop_16_dp.toString(),
            bop_16_p: bop_16_p.toString(),
            bop_16_mp: bop_16_mp.toString(),
            pi_16_dp: pi_16_dp.toString(),
            pi_16_p: pi_16_p.toString(),
            pi_16_mp: pi_16_mp.toString(),
            gm_16_db: encodeURIComponent(document.forms[0]["gm_16_db"].value),
            gm_16_b: encodeURIComponent(document.forms[0]["gm_16_b"].value),
            gm_16_mb: encodeURIComponent(document.forms[0]["gm_16_mb"].value),
            pd_16_db: encodeURIComponent(document.forms[0]["pd_16_db"].value),
            pd_16_b: encodeURIComponent(document.forms[0]["pd_16_b"].value),
            pd_16_mb: encodeURIComponent(document.forms[0]["pd_16_mb"].value),
            gm_16_dp: encodeURIComponent(document.forms[0]["gm_16_dp"].value),
            gm_16_p: encodeURIComponent(document.forms[0]["gm_16_p"].value),
            gm_16_mp: encodeURIComponent(document.forms[0]["gm_16_mp"].value),
            pd_16_dp: encodeURIComponent(document.forms[0]["pd_16_dp"].value),
            pd_16_p: encodeURIComponent(document.forms[0]["pd_16_p"].value),
            pd_16_mp: encodeURIComponent(document.forms[0]["pd_16_mp"].value),
            note_16: encodeURIComponent(document.forms[0]["note_16"].value.slice(0, 5)),

            tooth_15: tooth_15.toString(),
            mobility_15: encodeURIComponent(document.forms[0]["mobility_15"].value),
            implant_15: Implantat_15.toString(),
            bop_15_db: bop_15_db.toString(),
            bop_15_b: bop_15_b.toString(),
            bop_15_mb: bop_15_mb.toString(),
            pi_15_db: pi_15_db.toString(),
            pi_15_b: pi_15_b.toString(),
            pi_15_mb: pi_15_mb.toString(),
            bop_15_dp: bop_15_dp.toString(),
            bop_15_p: bop_15_p.toString(),
            bop_15_mp: bop_15_mp.toString(),
            pi_15_dp: pi_15_dp.toString(),
            pi_15_p: pi_15_p.toString(),
            pi_15_mp: pi_15_mp.toString(),
            gm_15_db: encodeURIComponent(document.forms[0]["gm_15_db"].value),
            gm_15_b: encodeURIComponent(document.forms[0]["gm_15_b"].value),
            gm_15_mb: encodeURIComponent(document.forms[0]["gm_15_mb"].value),
            pd_15_db: encodeURIComponent(document.forms[0]["pd_15_db"].value),
            pd_15_b: encodeURIComponent(document.forms[0]["pd_15_b"].value),
            pd_15_mb: encodeURIComponent(document.forms[0]["pd_15_mb"].value),
            gm_15_dp: encodeURIComponent(document.forms[0]["gm_15_dp"].value),
            gm_15_p: encodeURIComponent(document.forms[0]["gm_15_p"].value),
            gm_15_mp: encodeURIComponent(document.forms[0]["gm_15_mp"].value),
            pd_15_dp: encodeURIComponent(document.forms[0]["pd_15_dp"].value),
            pd_15_p: encodeURIComponent(document.forms[0]["pd_15_p"].value),
            pd_15_mp: encodeURIComponent(document.forms[0]["pd_15_mp"].value),
            note_15: encodeURIComponent(document.forms[0]["note_15"].value.slice(0, 5)),
            
            tooth_14: tooth_14.toString(),
            mobility_14: encodeURIComponent(document.forms[0]["mobility_14"].value),
            furcation_14_dp: Furkation_14_dp.toString(),
            furcation_14_mp: Furkation_14_mp.toString(),
            implant_14: Implantat_14.toString(),
            bop_14_db: bop_14_db.toString(),
            bop_14_b: bop_14_b.toString(),
            bop_14_mb: bop_14_mb.toString(),
            pi_14_db: pi_14_db.toString(),
            pi_14_b: pi_14_b.toString(),
            pi_14_mb: pi_14_mb.toString(),
            bop_14_dp: bop_14_dp.toString(),
            bop_14_p: bop_14_p.toString(),
            bop_14_mp: bop_14_mp.toString(),
            pi_14_dp: pi_14_dp.toString(),
            pi_14_p: pi_14_p.toString(),
            pi_14_mp: pi_14_mp.toString(),
            gm_14_db: encodeURIComponent(document.forms[0]["gm_14_db"].value),
            gm_14_b: encodeURIComponent(document.forms[0]["gm_14_b"].value),
            gm_14_mb: encodeURIComponent(document.forms[0]["gm_14_mb"].value),
            pd_14_db: encodeURIComponent(document.forms[0]["pd_14_db"].value),
            pd_14_b: encodeURIComponent(document.forms[0]["pd_14_b"].value),
            pd_14_mb: encodeURIComponent(document.forms[0]["pd_14_mb"].value),
            gm_14_dp: encodeURIComponent(document.forms[0]["gm_14_dp"].value),
            gm_14_p: encodeURIComponent(document.forms[0]["gm_14_p"].value),
            gm_14_mp: encodeURIComponent(document.forms[0]["gm_14_mp"].value),
            pd_14_dp: encodeURIComponent(document.forms[0]["pd_14_dp"].value),
            pd_14_p: encodeURIComponent(document.forms[0]["pd_14_p"].value),
            pd_14_mp: encodeURIComponent(document.forms[0]["pd_14_mp"].value),
            note_14: encodeURIComponent(document.forms[0]["note_14"].value.slice(0, 5)),
            
            tooth_13: tooth_13.toString(),
            mobility_13: encodeURIComponent(document.forms[0]["mobility_13"].value),
            implant_13: Implantat_13.toString(),
            bop_13_db: bop_13_db.toString(),
            bop_13_b: bop_13_b.toString(),
            bop_13_mb: bop_13_mb.toString(),
            pi_13_db: pi_13_db.toString(),
            pi_13_b: pi_13_b.toString(),
            pi_13_mb: pi_13_mb.toString(),
            bop_13_dp: bop_13_dp.toString(),
            bop_13_p: bop_13_p.toString(),
            bop_13_mp: bop_13_mp.toString(),
            pi_13_dp: pi_13_dp.toString(),
            pi_13_p: pi_13_p.toString(),
            pi_13_mp: pi_13_mp.toString(),
            gm_13_db: encodeURIComponent(document.forms[0]["gm_13_db"].value),
            gm_13_b: encodeURIComponent(document.forms[0]["gm_13_b"].value),
            gm_13_mb: encodeURIComponent(document.forms[0]["gm_13_mb"].value),
            pd_13_db: encodeURIComponent(document.forms[0]["pd_13_db"].value),
            pd_13_b: encodeURIComponent(document.forms[0]["pd_13_b"].value),
            pd_13_mb: encodeURIComponent(document.forms[0]["pd_13_mb"].value),
            gm_13_dp: encodeURIComponent(document.forms[0]["gm_13_dp"].value),
            gm_13_p: encodeURIComponent(document.forms[0]["gm_13_p"].value),
            gm_13_mp: encodeURIComponent(document.forms[0]["gm_13_mp"].value),
            pd_13_dp: encodeURIComponent(document.forms[0]["pd_13_dp"].value),
            pd_13_p: encodeURIComponent(document.forms[0]["pd_13_p"].value),
            pd_13_mp: encodeURIComponent(document.forms[0]["pd_13_mp"].value),
            note_13: encodeURIComponent(document.forms[0]["note_13"].value.slice(0, 5)),
            
            tooth_12: tooth_12.toString(),
            mobility_12: encodeURIComponent(document.forms[0]["mobility_12"].value),
            implant_12: Implantat_12.toString(),
            bop_12_db: bop_12_db.toString(),
            bop_12_b: bop_12_b.toString(),
            bop_12_mb: bop_12_mb.toString(),
            pi_12_db: pi_12_db.toString(),
            pi_12_b: pi_12_b.toString(),
            pi_12_mb: pi_12_mb.toString(),
            bop_12_dp: bop_12_dp.toString(),
            bop_12_p: bop_12_p.toString(),
            bop_12_mp: bop_12_mp.toString(),
            pi_12_dp: pi_12_dp.toString(),
            pi_12_p: pi_12_p.toString(),
            pi_12_mp: pi_12_mp.toString(),
            gm_12_db: encodeURIComponent(document.forms[0]["gm_12_db"].value),
            gm_12_b: encodeURIComponent(document.forms[0]["gm_12_b"].value),
            gm_12_mb: encodeURIComponent(document.forms[0]["gm_12_mb"].value),
            pd_12_db: encodeURIComponent(document.forms[0]["pd_12_db"].value),
            pd_12_b: encodeURIComponent(document.forms[0]["pd_12_b"].value),
            pd_12_mb: encodeURIComponent(document.forms[0]["pd_12_mb"].value),
            gm_12_dp: encodeURIComponent(document.forms[0]["gm_12_dp"].value),
            gm_12_p: encodeURIComponent(document.forms[0]["gm_12_p"].value),
            gm_12_mp: encodeURIComponent(document.forms[0]["gm_12_mp"].value),
            pd_12_dp: encodeURIComponent(document.forms[0]["pd_12_dp"].value),
            pd_12_p: encodeURIComponent(document.forms[0]["pd_12_p"].value),
            pd_12_mp: encodeURIComponent(document.forms[0]["pd_12_mp"].value),
            note_12: encodeURIComponent(document.forms[0]["note_12"].value.slice(0, 5)),
            
            tooth_11: tooth_11.toString(),
            mobility_11: encodeURIComponent(document.forms[0]["mobility_11"].value),
            implant_11: Implantat_11.toString(),
            bop_11_db: bop_11_db.toString(),
            bop_11_b: bop_11_b.toString(),
            bop_11_mb: bop_11_mb.toString(),
            pi_11_db: pi_11_db.toString(),
            pi_11_b: pi_11_b.toString(),
            pi_11_mb: pi_11_mb.toString(),
            bop_11_dp: bop_11_dp.toString(),
            bop_11_p: bop_11_p.toString(),
            bop_11_mp: bop_11_mp.toString(),
            pi_11_dp: pi_11_dp.toString(),
            pi_11_p: pi_11_p.toString(),
            pi_11_mp: pi_11_mp.toString(),
            gm_11_db: encodeURIComponent(document.forms[0]["gm_11_db"].value),
            gm_11_b: encodeURIComponent(document.forms[0]["gm_11_b"].value),
            gm_11_mb: encodeURIComponent(document.forms[0]["gm_11_mb"].value),
            pd_11_db: encodeURIComponent(document.forms[0]["pd_11_db"].value),
            pd_11_b: encodeURIComponent(document.forms[0]["pd_11_b"].value),
            pd_11_mb: encodeURIComponent(document.forms[0]["pd_11_mb"].value),
            gm_11_dp: encodeURIComponent(document.forms[0]["gm_11_dp"].value),
            gm_11_p: encodeURIComponent(document.forms[0]["gm_11_p"].value),
            gm_11_mp: encodeURIComponent(document.forms[0]["gm_11_mp"].value),
            pd_11_dp: encodeURIComponent(document.forms[0]["pd_11_dp"].value),
            pd_11_p: encodeURIComponent(document.forms[0]["pd_11_p"].value),
            pd_11_mp: encodeURIComponent(document.forms[0]["pd_11_mp"].value),
            note_11: encodeURIComponent(document.forms[0]["note_11"].value.slice(0, 5)),

            tooth_28: tooth_28.toString(),
            mobility_28: encodeURIComponent(document.forms[0]["mobility_28"].value),
            furcation_28_b: Furkation_28_b.toString(),
            furcation_28_dp: Furkation_28_dp.toString(),
            furcation_28_mp: Furkation_28_mp.toString(),
            implant_28: Implantat_28.toString(),
            bop_28_db: bop_28_db.toString(),
            bop_28_b: bop_28_b.toString(),
            bop_28_mb: bop_28_mb.toString(),
            pi_28_db: pi_28_db.toString(),
            pi_28_b: pi_28_b.toString(),
            pi_28_mb: pi_28_mb.toString(),
            bop_28_dp: bop_28_dp.toString(),
            bop_28_p: bop_28_p.toString(),
            bop_28_mp: bop_28_mp.toString(),
            pi_28_dp: pi_28_dp.toString(),
            pi_28_p: pi_28_p.toString(),
            pi_28_mp: pi_28_mp.toString(),
            gm_28_db: encodeURIComponent(document.forms[0]["gm_28_db"].value),
            gm_28_b: encodeURIComponent(document.forms[0]["gm_28_b"].value),
            gm_28_mb: encodeURIComponent(document.forms[0]["gm_28_mb"].value),
            pd_28_db: encodeURIComponent(document.forms[0]["pd_28_db"].value),
            pd_28_b: encodeURIComponent(document.forms[0]["pd_28_b"].value),
            pd_28_mb: encodeURIComponent(document.forms[0]["pd_28_mb"].value),
            gm_28_dp: encodeURIComponent(document.forms[0]["gm_28_dp"].value),
            gm_28_p: encodeURIComponent(document.forms[0]["gm_28_p"].value),
            gm_28_mp: encodeURIComponent(document.forms[0]["gm_28_mp"].value),
            pd_28_dp: encodeURIComponent(document.forms[0]["pd_28_dp"].value),
            pd_28_p: encodeURIComponent(document.forms[0]["pd_28_p"].value),
            pd_28_mp: encodeURIComponent(document.forms[0]["pd_28_mp"].value),
            note_28: encodeURIComponent(document.forms[0]["note_28"].value.slice(0, 5)),

            tooth_27: tooth_27.toString(),
            mobility_27: encodeURIComponent(document.forms[0]["mobility_27"].value),
            furcation_27_b: Furkation_27_b.toString(),
            furcation_27_dp: Furkation_27_dp.toString(),
            furcation_27_mp: Furkation_27_mp.toString(),
            implant_27: Implantat_27.toString(),
            bop_27_db: bop_27_db.toString(),
            bop_27_b: bop_27_b.toString(),
            bop_27_mb: bop_27_mb.toString(),
            pi_27_db: pi_27_db.toString(),
            pi_27_b: pi_27_b.toString(),
            pi_27_mb: pi_27_mb.toString(),
            bop_27_dp: bop_27_dp.toString(),
            bop_27_p: bop_27_p.toString(),
            bop_27_mp: bop_27_mp.toString(),
            pi_27_dp: pi_27_dp.toString(),
            pi_27_p: pi_27_p.toString(),
            pi_27_mp: pi_27_mp.toString(),
            gm_27_db: encodeURIComponent(document.forms[0]["gm_27_db"].value),
            gm_27_b: encodeURIComponent(document.forms[0]["gm_27_b"].value),
            gm_27_mb: encodeURIComponent(document.forms[0]["gm_27_mb"].value),
            pd_27_db: encodeURIComponent(document.forms[0]["pd_27_db"].value),
            pd_27_b: encodeURIComponent(document.forms[0]["pd_27_b"].value),
            pd_27_mb: encodeURIComponent(document.forms[0]["pd_27_mb"].value),
            gm_27_dp: encodeURIComponent(document.forms[0]["gm_27_dp"].value),
            gm_27_p: encodeURIComponent(document.forms[0]["gm_27_p"].value),
            gm_27_mp: encodeURIComponent(document.forms[0]["gm_27_mp"].value),
            pd_27_dp: encodeURIComponent(document.forms[0]["pd_27_dp"].value),
            pd_27_p: encodeURIComponent(document.forms[0]["pd_27_p"].value),
            pd_27_mp: encodeURIComponent(document.forms[0]["pd_27_mp"].value),
            note_27: encodeURIComponent(document.forms[0]["note_27"].value.slice(0, 5)),

            tooth_26: tooth_26.toString(),
            mobility_26: encodeURIComponent(document.forms[0]["mobility_26"].value),
            furcation_26_b: Furkation_26_b.toString(),
            furcation_26_dp: Furkation_26_dp.toString(),
            furcation_26_mp: Furkation_26_mp.toString(),
            implant_26: Implantat_26.toString(),
            bop_26_db: bop_26_db.toString(),
            bop_26_b: bop_26_b.toString(),
            bop_26_mb: bop_26_mb.toString(),
            pi_26_db: pi_26_db.toString(),
            pi_26_b: pi_26_b.toString(),
            pi_26_mb: pi_26_mb.toString(),
            bop_26_dp: bop_26_dp.toString(),
            bop_26_p: bop_26_p.toString(),
            bop_26_mp: bop_26_mp.toString(),
            pi_26_dp: pi_26_dp.toString(),
            pi_26_p: pi_26_p.toString(),
            pi_26_mp: pi_26_mp.toString(),
            gm_26_db: encodeURIComponent(document.forms[0]["gm_26_db"].value),
            gm_26_b: encodeURIComponent(document.forms[0]["gm_26_b"].value),
            gm_26_mb: encodeURIComponent(document.forms[0]["gm_26_mb"].value),
            pd_26_db: encodeURIComponent(document.forms[0]["pd_26_db"].value),
            pd_26_b: encodeURIComponent(document.forms[0]["pd_26_b"].value),
            pd_26_mb: encodeURIComponent(document.forms[0]["pd_26_mb"].value),
            gm_26_dp: encodeURIComponent(document.forms[0]["gm_26_dp"].value),
            gm_26_p: encodeURIComponent(document.forms[0]["gm_26_p"].value),
            gm_26_mp: encodeURIComponent(document.forms[0]["gm_26_mp"].value),
            pd_26_dp: encodeURIComponent(document.forms[0]["pd_26_dp"].value),
            pd_26_p: encodeURIComponent(document.forms[0]["pd_26_p"].value),
            pd_26_mp: encodeURIComponent(document.forms[0]["pd_26_mp"].value),
            note_26: encodeURIComponent(document.forms[0]["note_26"].value.slice(0, 5)),

            tooth_25: tooth_25.toString(),
            mobility_25: encodeURIComponent(document.forms[0]["mobility_25"].value),
            implant_25: Implantat_25.toString(),
            bop_25_db: bop_25_db.toString(),
            bop_25_b: bop_25_b.toString(),
            bop_25_mb: bop_25_mb.toString(),
            pi_25_db: pi_25_db.toString(),
            pi_25_b: pi_25_b.toString(),
            pi_25_mb: pi_25_mb.toString(),
            bop_25_dp: bop_25_dp.toString(),
            bop_25_p: bop_25_p.toString(),
            bop_25_mp: bop_25_mp.toString(),
            pi_25_dp: pi_25_dp.toString(),
            pi_25_p: pi_25_p.toString(),
            pi_25_mp: pi_25_mp.toString(),
            gm_25_db: encodeURIComponent(document.forms[0]["gm_25_db"].value),
            gm_25_b: encodeURIComponent(document.forms[0]["gm_25_b"].value),
            gm_25_mb: encodeURIComponent(document.forms[0]["gm_25_mb"].value),
            pd_25_db: encodeURIComponent(document.forms[0]["pd_25_db"].value),
            pd_25_b: encodeURIComponent(document.forms[0]["pd_25_b"].value),
            pd_25_mb: encodeURIComponent(document.forms[0]["pd_25_mb"].value),
            gm_25_dp: encodeURIComponent(document.forms[0]["gm_25_dp"].value),
            gm_25_p: encodeURIComponent(document.forms[0]["gm_25_p"].value),
            gm_25_mp: encodeURIComponent(document.forms[0]["gm_25_mp"].value),
            pd_25_dp: encodeURIComponent(document.forms[0]["pd_25_dp"].value),
            pd_25_p: encodeURIComponent(document.forms[0]["pd_25_p"].value),
            pd_25_mp: encodeURIComponent(document.forms[0]["pd_25_mp"].value),
            note_25: encodeURIComponent(document.forms[0]["note_25"].value.slice(0, 5)),
            
            tooth_24: tooth_24.toString(),
            mobility_24: encodeURIComponent(document.forms[0]["mobility_24"].value),
            furcation_24_dp: Furkation_24_dp.toString(),
            furcation_24_mp: Furkation_24_mp.toString(),
            implant_24: Implantat_24.toString(),
            bop_24_db: bop_24_db.toString(),
            bop_24_b: bop_24_b.toString(),
            bop_24_mb: bop_24_mb.toString(),
            pi_24_db: pi_24_db.toString(),
            pi_24_b: pi_24_b.toString(),
            pi_24_mb: pi_24_mb.toString(),
            bop_24_dp: bop_24_dp.toString(),
            bop_24_p: bop_24_p.toString(),
            bop_24_mp: bop_24_mp.toString(),
            pi_24_dp: pi_24_dp.toString(),
            pi_24_p: pi_24_p.toString(),
            pi_24_mp: pi_24_mp.toString(),
            gm_24_db: encodeURIComponent(document.forms[0]["gm_24_db"].value),
            gm_24_b: encodeURIComponent(document.forms[0]["gm_24_b"].value),
            gm_24_mb: encodeURIComponent(document.forms[0]["gm_24_mb"].value),
            pd_24_db: encodeURIComponent(document.forms[0]["pd_24_db"].value),
            pd_24_b: encodeURIComponent(document.forms[0]["pd_24_b"].value),
            pd_24_mb: encodeURIComponent(document.forms[0]["pd_24_mb"].value),
            gm_24_dp: encodeURIComponent(document.forms[0]["gm_24_dp"].value),
            gm_24_p: encodeURIComponent(document.forms[0]["gm_24_p"].value),
            gm_24_mp: encodeURIComponent(document.forms[0]["gm_24_mp"].value),
            pd_24_dp: encodeURIComponent(document.forms[0]["pd_24_dp"].value),
            pd_24_p: encodeURIComponent(document.forms[0]["pd_24_p"].value),
            pd_24_mp: encodeURIComponent(document.forms[0]["pd_24_mp"].value),
            note_24: encodeURIComponent(document.forms[0]["note_24"].value.slice(0, 5)),
            
            tooth_23: tooth_23.toString(),
            mobility_23: encodeURIComponent(document.forms[0]["mobility_23"].value),
            implant_23: Implantat_23.toString(),
            bop_23_db: bop_23_db.toString(),
            bop_23_b: bop_23_b.toString(),
            bop_23_mb: bop_23_mb.toString(),
            pi_23_db: pi_23_db.toString(),
            pi_23_b: pi_23_b.toString(),
            pi_23_mb: pi_23_mb.toString(),
            bop_23_dp: bop_23_dp.toString(),
            bop_23_p: bop_23_p.toString(),
            bop_23_mp: bop_23_mp.toString(),
            pi_23_dp: pi_23_dp.toString(),
            pi_23_p: pi_23_p.toString(),
            pi_23_mp: pi_23_mp.toString(),
            gm_23_db: encodeURIComponent(document.forms[0]["gm_23_db"].value),
            gm_23_b: encodeURIComponent(document.forms[0]["gm_23_b"].value),
            gm_23_mb: encodeURIComponent(document.forms[0]["gm_23_mb"].value),
            pd_23_db: encodeURIComponent(document.forms[0]["pd_23_db"].value),
            pd_23_b: encodeURIComponent(document.forms[0]["pd_23_b"].value),
            pd_23_mb: encodeURIComponent(document.forms[0]["pd_23_mb"].value),
            gm_23_dp: encodeURIComponent(document.forms[0]["gm_23_dp"].value),
            gm_23_p: encodeURIComponent(document.forms[0]["gm_23_p"].value),
            gm_23_mp: encodeURIComponent(document.forms[0]["gm_23_mp"].value),
            pd_23_dp: encodeURIComponent(document.forms[0]["pd_23_dp"].value),
            pd_23_p: encodeURIComponent(document.forms[0]["pd_23_p"].value),
            pd_23_mp: encodeURIComponent(document.forms[0]["pd_23_mp"].value),
            note_23: encodeURIComponent(document.forms[0]["note_23"].value.slice(0, 5)),
            
            tooth_22: tooth_22.toString(),
            mobility_22: encodeURIComponent(document.forms[0]["mobility_22"].value),
            implant_22: Implantat_22.toString(),
            bop_22_db: bop_22_db.toString(),
            bop_22_b: bop_22_b.toString(),
            bop_22_mb: bop_22_mb.toString(),
            pi_22_db: pi_22_db.toString(),
            pi_22_b: pi_22_b.toString(),
            pi_22_mb: pi_22_mb.toString(),
            bop_22_dp: bop_22_dp.toString(),
            bop_22_p: bop_22_p.toString(),
            bop_22_mp: bop_22_mp.toString(),
            pi_22_dp: pi_22_dp.toString(),
            pi_22_p: pi_22_p.toString(),
            pi_22_mp: pi_22_mp.toString(),
            gm_22_db: encodeURIComponent(document.forms[0]["gm_22_db"].value),
            gm_22_b: encodeURIComponent(document.forms[0]["gm_22_b"].value),
            gm_22_mb: encodeURIComponent(document.forms[0]["gm_22_mb"].value),
            pd_22_db: encodeURIComponent(document.forms[0]["pd_22_db"].value),
            pd_22_b: encodeURIComponent(document.forms[0]["pd_22_b"].value),
            pd_22_mb: encodeURIComponent(document.forms[0]["pd_22_mb"].value),
            gm_22_dp: encodeURIComponent(document.forms[0]["gm_22_dp"].value),
            gm_22_p: encodeURIComponent(document.forms[0]["gm_22_p"].value),
            gm_22_mp: encodeURIComponent(document.forms[0]["gm_22_mp"].value),
            pd_22_dp: encodeURIComponent(document.forms[0]["pd_22_dp"].value),
            pd_22_p: encodeURIComponent(document.forms[0]["pd_22_p"].value),
            pd_22_mp: encodeURIComponent(document.forms[0]["pd_22_mp"].value),
            note_22: encodeURIComponent(document.forms[0]["note_22"].value.slice(0, 5)),
            
            tooth_21: tooth_21.toString(),
            mobility_21: encodeURIComponent(document.forms[0]["mobility_21"].value),
            implant_21: Implantat_21.toString(),
            bop_21_db: bop_21_db.toString(),
            bop_21_b: bop_21_b.toString(),
            bop_21_mb: bop_21_mb.toString(),
            pi_21_db: pi_21_db.toString(),
            pi_21_b: pi_21_b.toString(),
            pi_21_mb: pi_21_mb.toString(),
            bop_21_dp: bop_21_dp.toString(),
            bop_21_p: bop_21_p.toString(),
            bop_21_mp: bop_21_mp.toString(),
            pi_21_dp: pi_21_dp.toString(),
            pi_21_p: pi_21_p.toString(),
            pi_21_mp: pi_21_mp.toString(),
            gm_21_db: encodeURIComponent(document.forms[0]["gm_21_db"].value),
            gm_21_b: encodeURIComponent(document.forms[0]["gm_21_b"].value),
            gm_21_mb: encodeURIComponent(document.forms[0]["gm_21_mb"].value),
            pd_21_db: encodeURIComponent(document.forms[0]["pd_21_db"].value),
            pd_21_b: encodeURIComponent(document.forms[0]["pd_21_b"].value),
            pd_21_mb: encodeURIComponent(document.forms[0]["pd_21_mb"].value),
            gm_21_dp: encodeURIComponent(document.forms[0]["gm_21_dp"].value),
            gm_21_p: encodeURIComponent(document.forms[0]["gm_21_p"].value),
            gm_21_mp: encodeURIComponent(document.forms[0]["gm_21_mp"].value),
            pd_21_dp: encodeURIComponent(document.forms[0]["pd_21_dp"].value),
            pd_21_p: encodeURIComponent(document.forms[0]["pd_21_p"].value),
            pd_21_mp: encodeURIComponent(document.forms[0]["pd_21_mp"].value),
            note_21: encodeURIComponent(document.forms[0]["note_21"].value.slice(0, 5)),
            
            tooth_38: tooth_38.toString(),
            mobility_38: encodeURIComponent(document.forms[0]["mobility_38"].value),
            furcation_38_b: Furkation_38_b.toString(),
            furcation_38_l: Furkation_38_l.toString(),
            implant_38: Implantat_38.toString(),
            bop_38_db: bop_38_db.toString(),
            bop_38_b: bop_38_b.toString(),
            bop_38_mb: bop_38_mb.toString(),
            pi_38_db: pi_38_db.toString(),
            pi_38_b: pi_38_b.toString(),
            pi_38_mb: pi_38_mb.toString(),
            bop_38_dl: bop_38_dl.toString(),
            bop_38_l: bop_38_l.toString(),
            bop_38_ml: bop_38_ml.toString(),
            pi_38_dl: pi_38_dl.toString(),
            pi_38_l: pi_38_l.toString(),
            pi_38_ml: pi_38_ml.toString(),
            gm_38_db: encodeURIComponent(document.forms[0]["gm_38_db"].value),
            gm_38_b: encodeURIComponent(document.forms[0]["gm_38_b"].value),
            gm_38_mb: encodeURIComponent(document.forms[0]["gm_38_mb"].value),
            pd_38_db: encodeURIComponent(document.forms[0]["pd_38_db"].value),
            pd_38_b: encodeURIComponent(document.forms[0]["pd_38_b"].value),
            pd_38_mb: encodeURIComponent(document.forms[0]["pd_38_mb"].value),
            gm_38_dl: encodeURIComponent(document.forms[0]["gm_38_dl"].value),
            gm_38_l: encodeURIComponent(document.forms[0]["gm_38_l"].value),
            gm_38_ml: encodeURIComponent(document.forms[0]["gm_38_ml"].value),
            pd_38_dl: encodeURIComponent(document.forms[0]["pd_38_dl"].value),
            pd_38_l: encodeURIComponent(document.forms[0]["pd_38_l"].value),
            pd_38_ml: encodeURIComponent(document.forms[0]["pd_38_ml"].value),
            note_38: encodeURIComponent(document.forms[0]["note_38"].value.slice(0, 5)),

            tooth_37: tooth_37.toString(),
            mobility_37: encodeURIComponent(document.forms[0]["mobility_37"].value),
            furcation_37_b: Furkation_37_b.toString(),
            furcation_37_l: Furkation_37_l.toString(),
            implant_37: Implantat_37.toString(),
            bop_37_db: bop_37_db.toString(),
            bop_37_b: bop_37_b.toString(),

            bop_37_mb: bop_37_mb.toString(),
            pi_37_db: pi_37_db.toString(),
            pi_37_b: pi_37_b.toString(),
            pi_37_mb: pi_37_mb.toString(),
            bop_37_dl: bop_37_dl.toString(),
            bop_37_l: bop_37_l.toString(),
            bop_37_ml: bop_37_ml.toString(),
            pi_37_dl: pi_37_dl.toString(),
            pi_37_l: pi_37_l.toString(),
            pi_37_ml: pi_37_ml.toString(),
            gm_37_db: encodeURIComponent(document.forms[0]["gm_37_db"].value),
            gm_37_b: encodeURIComponent(document.forms[0]["gm_37_b"].value),
            gm_37_mb: encodeURIComponent(document.forms[0]["gm_37_mb"].value),
            pd_37_db: encodeURIComponent(document.forms[0]["pd_37_db"].value),
            pd_37_b: encodeURIComponent(document.forms[0]["pd_37_b"].value),
            pd_37_mb: encodeURIComponent(document.forms[0]["pd_37_mb"].value),
            gm_37_dl: encodeURIComponent(document.forms[0]["gm_37_dl"].value),
            gm_37_l: encodeURIComponent(document.forms[0]["gm_37_l"].value),
            gm_37_ml: encodeURIComponent(document.forms[0]["gm_37_ml"].value),
            pd_37_dl: encodeURIComponent(document.forms[0]["pd_37_dl"].value),
            pd_37_l: encodeURIComponent(document.forms[0]["pd_37_l"].value),
            pd_37_ml: encodeURIComponent(document.forms[0]["pd_37_ml"].value),
            note_37: encodeURIComponent(document.forms[0]["note_37"].value.slice(0, 5)),

            tooth_36: tooth_36.toString(),
            mobility_36: encodeURIComponent(document.forms[0]["mobility_36"].value),
            furcation_36_b: Furkation_36_b.toString(),
            furcation_36_l: Furkation_36_l.toString(),
            implant_36: Implantat_36.toString(),
            bop_36_db: bop_36_db.toString(),
            bop_36_b: bop_36_b.toString(),
            bop_36_mb: bop_36_mb.toString(),
            pi_36_db: pi_36_db.toString(),
            pi_36_b: pi_36_b.toString(),
            pi_36_mb: pi_36_mb.toString(),
            bop_36_dl: bop_36_dl.toString(),
            bop_36_l: bop_36_l.toString(),
            bop_36_ml: bop_36_ml.toString(),
            pi_36_dl: pi_36_dl.toString(),
            pi_36_l: pi_36_l.toString(),
            pi_36_ml: pi_36_ml.toString(),
            gm_36_db: encodeURIComponent(document.forms[0]["gm_36_db"].value),
            gm_36_b: encodeURIComponent(document.forms[0]["gm_36_b"].value),
            gm_36_mb: encodeURIComponent(document.forms[0]["gm_36_mb"].value),
            pd_36_db: encodeURIComponent(document.forms[0]["pd_36_db"].value),
            pd_36_b: encodeURIComponent(document.forms[0]["pd_36_b"].value),
            pd_36_mb: encodeURIComponent(document.forms[0]["pd_36_mb"].value),
            gm_36_dl: encodeURIComponent(document.forms[0]["gm_36_dl"].value),
            gm_36_l: encodeURIComponent(document.forms[0]["gm_36_l"].value),
            gm_36_ml: encodeURIComponent(document.forms[0]["gm_36_ml"].value),
            pd_36_dl: encodeURIComponent(document.forms[0]["pd_36_dl"].value),
            pd_36_l: encodeURIComponent(document.forms[0]["pd_36_l"].value),
            pd_36_ml: encodeURIComponent(document.forms[0]["pd_36_ml"].value),
            note_36: encodeURIComponent(document.forms[0]["note_36"].value.slice(0, 5)),

            tooth_35: tooth_35.toString(),
            mobility_35: encodeURIComponent(document.forms[0]["mobility_35"].value),
            implant_35: Implantat_35.toString(),
            bop_35_db: bop_35_db.toString(),
            bop_35_b: bop_35_b.toString(),
            bop_35_mb: bop_35_mb.toString(),
            pi_35_db: pi_35_db.toString(),
            pi_35_b: pi_35_b.toString(),
            pi_35_mb: pi_35_mb.toString(),
            bop_35_dl: bop_35_dl.toString(),
            bop_35_l: bop_35_l.toString(),
            bop_35_ml: bop_35_ml.toString(),
            pi_35_dl: pi_35_dl.toString(),
            pi_35_l: pi_35_l.toString(),
            pi_35_ml: pi_35_ml.toString(),
            gm_35_db: encodeURIComponent(document.forms[0]["gm_35_db"].value),
            gm_35_b: encodeURIComponent(document.forms[0]["gm_35_b"].value),
            gm_35_mb: encodeURIComponent(document.forms[0]["gm_35_mb"].value),
            pd_35_db: encodeURIComponent(document.forms[0]["pd_35_db"].value),
            pd_35_b: encodeURIComponent(document.forms[0]["pd_35_b"].value),
            pd_35_mb: encodeURIComponent(document.forms[0]["pd_35_mb"].value),
            gm_35_dl: encodeURIComponent(document.forms[0]["gm_35_dl"].value),
            gm_35_l: encodeURIComponent(document.forms[0]["gm_35_l"].value),
            gm_35_ml: encodeURIComponent(document.forms[0]["gm_35_ml"].value),
            pd_35_dl: encodeURIComponent(document.forms[0]["pd_35_dl"].value),
            pd_35_l: encodeURIComponent(document.forms[0]["pd_35_l"].value),
            pd_35_ml: encodeURIComponent(document.forms[0]["pd_35_ml"].value),
            note_35: encodeURIComponent(document.forms[0]["note_35"].value.slice(0, 5)),
            
            tooth_34: tooth_34.toString(),
            mobility_34: encodeURIComponent(document.forms[0]["mobility_34"].value),
            implant_34: Implantat_34.toString(),
            bop_34_db: bop_34_db.toString(),
            bop_34_b: bop_34_b.toString(),
            bop_34_mb: bop_34_mb.toString(),
            pi_34_db: pi_34_db.toString(),
            pi_34_b: pi_34_b.toString(),
            pi_34_mb: pi_34_mb.toString(),
            bop_34_dl: bop_34_dl.toString(),
            bop_34_l: bop_34_l.toString(),
            bop_34_ml: bop_34_ml.toString(),
            pi_34_dl: pi_34_dl.toString(),
            pi_34_l: pi_34_l.toString(),
            pi_34_ml: pi_34_ml.toString(),
            gm_34_db: encodeURIComponent(document.forms[0]["gm_34_db"].value),
            gm_34_b: encodeURIComponent(document.forms[0]["gm_34_b"].value),
            gm_34_mb: encodeURIComponent(document.forms[0]["gm_34_mb"].value),
            pd_34_db: encodeURIComponent(document.forms[0]["pd_34_db"].value),
            pd_34_b: encodeURIComponent(document.forms[0]["pd_34_b"].value),
            pd_34_mb: encodeURIComponent(document.forms[0]["pd_34_mb"].value),
            gm_34_dl: encodeURIComponent(document.forms[0]["gm_34_dl"].value),
            gm_34_l: encodeURIComponent(document.forms[0]["gm_34_l"].value),
            gm_34_ml: encodeURIComponent(document.forms[0]["gm_34_ml"].value),
            pd_34_dl: encodeURIComponent(document.forms[0]["pd_34_dl"].value),
            pd_34_l: encodeURIComponent(document.forms[0]["pd_34_l"].value),
            pd_34_ml: encodeURIComponent(document.forms[0]["pd_34_ml"].value),
            note_34: encodeURIComponent(document.forms[0]["note_34"].value.slice(0, 5)),
            
            tooth_33: tooth_33.toString(),
            mobility_33: encodeURIComponent(document.forms[0]["mobility_33"].value),
            implant_33: Implantat_33.toString(),
            bop_33_db: bop_33_db.toString(),
            bop_33_b: bop_33_b.toString(),
            bop_33_mb: bop_33_mb.toString(),
            pi_33_db: pi_33_db.toString(),
            pi_33_b: pi_33_b.toString(),
            pi_33_mb: pi_33_mb.toString(),
            bop_33_dl: bop_33_dl.toString(),
            bop_33_l: bop_33_l.toString(),
            bop_33_ml: bop_33_ml.toString(),
            pi_33_dl: pi_33_dl.toString(),
            pi_33_l: pi_33_l.toString(),
            pi_33_ml: pi_33_ml.toString(),
            gm_33_db: encodeURIComponent(document.forms[0]["gm_33_db"].value),
            gm_33_b: encodeURIComponent(document.forms[0]["gm_33_b"].value),
            gm_33_mb: encodeURIComponent(document.forms[0]["gm_33_mb"].value),
            pd_33_db: encodeURIComponent(document.forms[0]["pd_33_db"].value),
            pd_33_b: encodeURIComponent(document.forms[0]["pd_33_b"].value),
            pd_33_mb: encodeURIComponent(document.forms[0]["pd_33_mb"].value),
            gm_33_dl: encodeURIComponent(document.forms[0]["gm_33_dl"].value),
            gm_33_l: encodeURIComponent(document.forms[0]["gm_33_l"].value),
            gm_33_ml: encodeURIComponent(document.forms[0]["gm_33_ml"].value),
            pd_33_dl: encodeURIComponent(document.forms[0]["pd_33_dl"].value),
            pd_33_l: encodeURIComponent(document.forms[0]["pd_33_l"].value),
            pd_33_ml: encodeURIComponent(document.forms[0]["pd_33_ml"].value),
            note_33: encodeURIComponent(document.forms[0]["note_33"].value.slice(0, 5)),
            
            tooth_32: tooth_32.toString(),
            mobility_32: encodeURIComponent(document.forms[0]["mobility_32"].value),
            implant_32: Implantat_32.toString(),
            bop_32_db: bop_32_db.toString(),
            bop_32_b: bop_32_b.toString(),
            bop_32_mb: bop_32_mb.toString(),
            pi_32_db: pi_32_db.toString(),
            pi_32_b: pi_32_b.toString(),
            pi_32_mb: pi_32_mb.toString(),
            bop_32_dl: bop_32_dl.toString(),
            bop_32_l: bop_32_l.toString(),
            bop_32_ml: bop_32_ml.toString(),
            pi_32_dl: pi_32_dl.toString(),
            pi_32_l: pi_32_l.toString(),
            pi_32_ml: pi_32_ml.toString(),
            gm_32_db: encodeURIComponent(document.forms[0]["gm_32_db"].value),
            gm_32_b: encodeURIComponent(document.forms[0]["gm_32_b"].value),
            gm_32_mb: encodeURIComponent(document.forms[0]["gm_32_mb"].value),
            pd_32_db: encodeURIComponent(document.forms[0]["pd_32_db"].value),
            pd_32_b: encodeURIComponent(document.forms[0]["pd_32_b"].value),
            pd_32_mb: encodeURIComponent(document.forms[0]["pd_32_mb"].value),
            gm_32_dl: encodeURIComponent(document.forms[0]["gm_32_dl"].value),
            gm_32_l: encodeURIComponent(document.forms[0]["gm_32_l"].value),
            gm_32_ml: encodeURIComponent(document.forms[0]["gm_32_ml"].value),
            pd_32_dl: encodeURIComponent(document.forms[0]["pd_32_dl"].value),
            pd_32_l: encodeURIComponent(document.forms[0]["pd_32_l"].value),
            pd_32_ml: encodeURIComponent(document.forms[0]["pd_32_ml"].value),
            note_32: encodeURIComponent(document.forms[0]["note_32"].value.slice(0, 5)),
            
            tooth_31: tooth_31.toString(),
            mobility_31: encodeURIComponent(document.forms[0]["mobility_31"].value),
            implant_31: Implantat_31.toString(),
            bop_31_db: bop_31_db.toString(),
            bop_31_b: bop_31_b.toString(),
            bop_31_mb: bop_31_mb.toString(),
            pi_31_db: pi_31_db.toString(),
            pi_31_b: pi_31_b.toString(),
            pi_31_mb: pi_31_mb.toString(),
            bop_31_dl: bop_31_dl.toString(),
            bop_31_l: bop_31_l.toString(),
            bop_31_ml: bop_31_ml.toString(),
            pi_31_dl: pi_31_dl.toString(),
            pi_31_l: pi_31_l.toString(),
            pi_31_ml: pi_31_ml.toString(),
            gm_31_db: encodeURIComponent(document.forms[0]["gm_31_db"].value),
            gm_31_b: encodeURIComponent(document.forms[0]["gm_31_b"].value),
            gm_31_mb: encodeURIComponent(document.forms[0]["gm_31_mb"].value),
            pd_31_db: encodeURIComponent(document.forms[0]["pd_31_db"].value),
            pd_31_b: encodeURIComponent(document.forms[0]["pd_31_b"].value),
            pd_31_mb: encodeURIComponent(document.forms[0]["pd_31_mb"].value),
            gm_31_dl: encodeURIComponent(document.forms[0]["gm_31_dl"].value),
            gm_31_l: encodeURIComponent(document.forms[0]["gm_31_l"].value),
            gm_31_ml: encodeURIComponent(document.forms[0]["gm_31_ml"].value),
            pd_31_dl: encodeURIComponent(document.forms[0]["pd_31_dl"].value),
            pd_31_l: encodeURIComponent(document.forms[0]["pd_31_l"].value),
            pd_31_ml: encodeURIComponent(document.forms[0]["pd_31_ml"].value),
            note_31: encodeURIComponent(document.forms[0]["note_31"].value.slice(0, 5)),

            tooth_48: tooth_48.toString(),
            mobility_48: encodeURIComponent(document.forms[0]["mobility_48"].value),
            furcation_48_b: Furkation_48_b.toString(),
            furcation_48_l: Furkation_48_l.toString(),
            implant_48: Implantat_48.toString(),
            bop_48_db: bop_48_db.toString(),
            bop_48_b: bop_48_b.toString(),
            bop_48_mb: bop_48_mb.toString(),
            pi_48_db: pi_48_db.toString(),
            pi_48_b: pi_48_b.toString(),
            pi_48_mb: pi_48_mb.toString(),
            bop_48_dl: bop_48_dl.toString(),
            bop_48_l: bop_48_l.toString(),
            bop_48_ml: bop_48_ml.toString(),
            pi_48_dl: pi_48_dl.toString(),
            pi_48_l: pi_48_l.toString(),
            pi_48_ml: pi_48_ml.toString(),
            gm_48_db: encodeURIComponent(document.forms[0]["gm_48_db"].value),
            gm_48_b: encodeURIComponent(document.forms[0]["gm_48_b"].value),
            gm_48_mb: encodeURIComponent(document.forms[0]["gm_48_mb"].value),
            pd_48_db: encodeURIComponent(document.forms[0]["pd_48_db"].value),
            pd_48_b: encodeURIComponent(document.forms[0]["pd_48_b"].value),
            pd_48_mb: encodeURIComponent(document.forms[0]["pd_48_mb"].value),
            gm_48_dl: encodeURIComponent(document.forms[0]["gm_48_dl"].value),
            gm_48_l: encodeURIComponent(document.forms[0]["gm_48_l"].value),
            gm_48_ml: encodeURIComponent(document.forms[0]["gm_48_ml"].value),
            pd_48_dl: encodeURIComponent(document.forms[0]["pd_48_dl"].value),
            pd_48_l: encodeURIComponent(document.forms[0]["pd_48_l"].value),
            pd_48_ml: encodeURIComponent(document.forms[0]["pd_48_ml"].value),
            note_48: encodeURIComponent(document.forms[0]["note_48"].value.slice(0, 5)),

            tooth_47: tooth_47.toString(),
            mobility_47: encodeURIComponent(document.forms[0]["mobility_47"].value),
            furcation_47_b: Furkation_47_b.toString(),
            furcation_47_l: Furkation_47_l.toString(),
            implant_47: Implantat_47.toString(),
            bop_47_db: bop_47_db.toString(),
            bop_47_b: bop_47_b.toString(),
            bop_47_mb: bop_47_mb.toString(),
            pi_47_db: pi_47_db.toString(),
            pi_47_b: pi_47_b.toString(),
            pi_47_mb: pi_47_mb.toString(),
            bop_47_dl: bop_47_dl.toString(),
            bop_47_l: bop_47_l.toString(),
            bop_47_ml: bop_47_ml.toString(),
            pi_47_dl: pi_47_dl.toString(),
            pi_47_l: pi_47_l.toString(),
            pi_47_ml: pi_47_ml.toString(),
            gm_47_db: encodeURIComponent(document.forms[0]["gm_47_db"].value),
            gm_47_b: encodeURIComponent(document.forms[0]["gm_47_b"].value),
            gm_47_mb: encodeURIComponent(document.forms[0]["gm_47_mb"].value),
            pd_47_db: encodeURIComponent(document.forms[0]["pd_47_db"].value),
            pd_47_b: encodeURIComponent(document.forms[0]["pd_47_b"].value),
            pd_47_mb: encodeURIComponent(document.forms[0]["pd_47_mb"].value),
            gm_47_dl: encodeURIComponent(document.forms[0]["gm_47_dl"].value),
            gm_47_l: encodeURIComponent(document.forms[0]["gm_47_l"].value),
            gm_47_ml: encodeURIComponent(document.forms[0]["gm_47_ml"].value),
            pd_47_dl: encodeURIComponent(document.forms[0]["pd_47_dl"].value),
            pd_47_l: encodeURIComponent(document.forms[0]["pd_47_l"].value),
            pd_47_ml: encodeURIComponent(document.forms[0]["pd_47_ml"].value),
            note_47: encodeURIComponent(document.forms[0]["note_47"].value.slice(0, 5)),

            tooth_46: tooth_46.toString(),
            mobility_46: encodeURIComponent(document.forms[0]["mobility_46"].value),
            furcation_46_b: Furkation_46_b.toString(),
            furcation_46_l: Furkation_46_l.toString(),
            implant_46: Implantat_46.toString(),
            bop_46_db: bop_46_db.toString(),
            bop_46_b: bop_46_b.toString(),
            bop_46_mb: bop_46_mb.toString(),
            pi_46_db: pi_46_db.toString(),
            pi_46_b: pi_46_b.toString(),
            pi_46_mb: pi_46_mb.toString(),
            bop_46_dl: bop_46_dl.toString(),
            bop_46_l: bop_46_l.toString(),
            bop_46_ml: bop_46_ml.toString(),
            pi_46_dl: pi_46_dl.toString(),
            pi_46_l: pi_46_l.toString(),
            pi_46_ml: pi_46_ml.toString(),
            gm_46_db: encodeURIComponent(document.forms[0]["gm_46_db"].value),
            gm_46_b: encodeURIComponent(document.forms[0]["gm_46_b"].value),
            gm_46_mb: encodeURIComponent(document.forms[0]["gm_46_mb"].value),
            pd_46_db: encodeURIComponent(document.forms[0]["pd_46_db"].value),
            pd_46_b: encodeURIComponent(document.forms[0]["pd_46_b"].value),
            pd_46_mb: encodeURIComponent(document.forms[0]["pd_46_mb"].value),
            gm_46_dl: encodeURIComponent(document.forms[0]["gm_46_dl"].value),
            gm_46_l: encodeURIComponent(document.forms[0]["gm_46_l"].value),
            gm_46_ml: encodeURIComponent(document.forms[0]["gm_46_ml"].value),
            pd_46_dl: encodeURIComponent(document.forms[0]["pd_46_dl"].value),
            pd_46_l: encodeURIComponent(document.forms[0]["pd_46_l"].value),
            pd_46_ml: encodeURIComponent(document.forms[0]["pd_46_ml"].value),
            note_46: encodeURIComponent(document.forms[0]["note_46"].value.slice(0, 5)),

            tooth_45: tooth_45.toString(),
            mobility_45: encodeURIComponent(document.forms[0]["mobility_45"].value),
            implant_45: Implantat_45.toString(),
            bop_45_db: bop_45_db.toString(),
            bop_45_b: bop_45_b.toString(),
            bop_45_mb: bop_45_mb.toString(),
            pi_45_db: pi_45_db.toString(),
            pi_45_b: pi_45_b.toString(),
            pi_45_mb: pi_45_mb.toString(),
            bop_45_dl: bop_45_dl.toString(),
            bop_45_l: bop_45_l.toString(),
            bop_45_ml: bop_45_ml.toString(),
            pi_45_dl: pi_45_dl.toString(),
            pi_45_l: pi_45_l.toString(),
            pi_45_ml: pi_45_ml.toString(),
            gm_45_db: encodeURIComponent(document.forms[0]["gm_45_db"].value),
            gm_45_b: encodeURIComponent(document.forms[0]["gm_45_b"].value),
            gm_45_mb: encodeURIComponent(document.forms[0]["gm_45_mb"].value),
            pd_45_db: encodeURIComponent(document.forms[0]["pd_45_db"].value),
            pd_45_b: encodeURIComponent(document.forms[0]["pd_45_b"].value),
            pd_45_mb: encodeURIComponent(document.forms[0]["pd_45_mb"].value),
            gm_45_dl: encodeURIComponent(document.forms[0]["gm_45_dl"].value),
            gm_45_l: encodeURIComponent(document.forms[0]["gm_45_l"].value),
            gm_45_ml: encodeURIComponent(document.forms[0]["gm_45_ml"].value),
            pd_45_dl: encodeURIComponent(document.forms[0]["pd_45_dl"].value),
            pd_45_l: encodeURIComponent(document.forms[0]["pd_45_l"].value),
            pd_45_ml: encodeURIComponent(document.forms[0]["pd_45_ml"].value),
            note_45: encodeURIComponent(document.forms[0]["note_45"].value.slice(0, 5)),
            
            tooth_44: tooth_44.toString(),
            mobility_44: encodeURIComponent(document.forms[0]["mobility_44"].value),
            implant_44: Implantat_44.toString(),
            bop_44_db: bop_44_db.toString(),
            bop_44_b: bop_44_b.toString(),
            bop_44_mb: bop_44_mb.toString(),
            pi_44_db: pi_44_db.toString(),
            pi_44_b: pi_44_b.toString(),
            pi_44_mb: pi_44_mb.toString(),
            bop_44_dl: bop_44_dl.toString(),
            bop_44_l: bop_44_l.toString(),
            bop_44_ml: bop_44_ml.toString(),
            pi_44_dl: pi_44_dl.toString(),
            pi_44_l: pi_44_l.toString(),
            pi_44_ml: pi_44_ml.toString(),
            gm_44_db: encodeURIComponent(document.forms[0]["gm_44_db"].value),
            gm_44_b: encodeURIComponent(document.forms[0]["gm_44_b"].value),
            gm_44_mb: encodeURIComponent(document.forms[0]["gm_44_mb"].value),
            pd_44_db: encodeURIComponent(document.forms[0]["pd_44_db"].value),
            pd_44_b: encodeURIComponent(document.forms[0]["pd_44_b"].value),
            pd_44_mb: encodeURIComponent(document.forms[0]["pd_44_mb"].value),
            gm_44_dl: encodeURIComponent(document.forms[0]["gm_44_dl"].value),
            gm_44_l: encodeURIComponent(document.forms[0]["gm_44_l"].value),
            gm_44_ml: encodeURIComponent(document.forms[0]["gm_44_ml"].value),
            pd_44_dl: encodeURIComponent(document.forms[0]["pd_44_dl"].value),
            pd_44_l: encodeURIComponent(document.forms[0]["pd_44_l"].value),
            pd_44_ml: encodeURIComponent(document.forms[0]["pd_44_ml"].value),
            note_44: encodeURIComponent(document.forms[0]["note_44"].value.slice(0, 5)),
            
            tooth_43: tooth_43.toString(),
            mobility_43: encodeURIComponent(document.forms[0]["mobility_43"].value),
            implant_43: Implantat_43.toString(),
            bop_43_db: bop_43_db.toString(),
            bop_43_b: bop_43_b.toString(),
            bop_43_mb: bop_43_mb.toString(),
            pi_43_db: pi_43_db.toString(),
            pi_43_b: pi_43_b.toString(),
            pi_43_mb: pi_43_mb.toString(),
            bop_43_dl: bop_43_dl.toString(),
            bop_43_l: bop_43_l.toString(),
            bop_43_ml: bop_43_ml.toString(),
            pi_43_dl: pi_43_dl.toString(),
            pi_43_l: pi_43_l.toString(),
            pi_43_ml: pi_43_ml.toString(),
            gm_43_db: encodeURIComponent(document.forms[0]["gm_43_db"].value),
            gm_43_b: encodeURIComponent(document.forms[0]["gm_43_b"].value),
            gm_43_mb: encodeURIComponent(document.forms[0]["gm_43_mb"].value),
            pd_43_db: encodeURIComponent(document.forms[0]["pd_43_db"].value),
            pd_43_b: encodeURIComponent(document.forms[0]["pd_43_b"].value),
            pd_43_mb: encodeURIComponent(document.forms[0]["pd_43_mb"].value),
            gm_43_dl: encodeURIComponent(document.forms[0]["gm_43_dl"].value),
            gm_43_l: encodeURIComponent(document.forms[0]["gm_43_l"].value),
            gm_43_ml: encodeURIComponent(document.forms[0]["gm_43_ml"].value),
            pd_43_dl: encodeURIComponent(document.forms[0]["pd_43_dl"].value),
            pd_43_l: encodeURIComponent(document.forms[0]["pd_43_l"].value),
            pd_43_ml: encodeURIComponent(document.forms[0]["pd_43_ml"].value),
            note_43: encodeURIComponent(document.forms[0]["note_43"].value.slice(0, 5)),
            
            tooth_42: tooth_42.toString(),
            mobility_42: encodeURIComponent(document.forms[0]["mobility_42"].value),
            implant_42: Implantat_42.toString(),
            bop_42_db: bop_42_db.toString(),
            bop_42_b: bop_42_b.toString(),
            bop_42_mb: bop_42_mb.toString(),
            pi_42_db: pi_42_db.toString(),
            pi_42_b: pi_42_b.toString(),
            pi_42_mb: pi_42_mb.toString(),
            bop_42_dl: bop_42_dl.toString(),
            bop_42_l: bop_42_l.toString(),
            bop_42_ml: bop_42_ml.toString(),
            pi_42_dl: pi_42_dl.toString(),
            pi_42_l: pi_42_l.toString(),
            pi_42_ml: pi_42_ml.toString(),
            gm_42_db: encodeURIComponent(document.forms[0]["gm_42_db"].value),
            gm_42_b: encodeURIComponent(document.forms[0]["gm_42_b"].value),
            gm_42_mb: encodeURIComponent(document.forms[0]["gm_42_mb"].value),
            pd_42_db: encodeURIComponent(document.forms[0]["pd_42_db"].value),
            pd_42_b: encodeURIComponent(document.forms[0]["pd_42_b"].value),
            pd_42_mb: encodeURIComponent(document.forms[0]["pd_42_mb"].value),
            gm_42_dl: encodeURIComponent(document.forms[0]["gm_42_dl"].value),
            gm_42_l: encodeURIComponent(document.forms[0]["gm_42_l"].value),
            gm_42_ml: encodeURIComponent(document.forms[0]["gm_42_ml"].value),
            pd_42_dl: encodeURIComponent(document.forms[0]["pd_42_dl"].value),
            pd_42_l: encodeURIComponent(document.forms[0]["pd_42_l"].value),
            pd_42_ml: encodeURIComponent(document.forms[0]["pd_42_ml"].value),
            note_42: encodeURIComponent(document.forms[0]["note_42"].value.slice(0, 5)),
            
            tooth_41: tooth_41.toString(),
            mobility_41: encodeURIComponent(document.forms[0]["mobility_41"].value),
            implant_41: Implantat_41.toString(),
            bop_41_db: bop_41_db.toString(),
            bop_41_b: bop_41_b.toString(),
            bop_41_mb: bop_41_mb.toString(),
            pi_41_db: pi_41_db.toString(),
            pi_41_b: pi_41_b.toString(),
            pi_41_mb: pi_41_mb.toString(),
            bop_41_dl: bop_41_dl.toString(),
            bop_41_l: bop_41_l.toString(),
            bop_41_ml: bop_41_ml.toString(),
            pi_41_dl: pi_41_dl.toString(),
            pi_41_l: pi_41_l.toString(),
            pi_41_ml: pi_41_ml.toString(),
            gm_41_db: encodeURIComponent(document.forms[0]["gm_41_db"].value),
            gm_41_b: encodeURIComponent(document.forms[0]["gm_41_b"].value),
            gm_41_mb: encodeURIComponent(document.forms[0]["gm_41_mb"].value),
            pd_41_db: encodeURIComponent(document.forms[0]["pd_41_db"].value),
            pd_41_b: encodeURIComponent(document.forms[0]["pd_41_b"].value),
            pd_41_mb: encodeURIComponent(document.forms[0]["pd_41_mb"].value),
            gm_41_dl: encodeURIComponent(document.forms[0]["gm_41_dl"].value),
            gm_41_l: encodeURIComponent(document.forms[0]["gm_41_l"].value),
            gm_41_ml: encodeURIComponent(document.forms[0]["gm_41_ml"].value),
            pd_41_dl: encodeURIComponent(document.forms[0]["pd_41_dl"].value),
            pd_41_l: encodeURIComponent(document.forms[0]["pd_41_l"].value),
            pd_41_ml: encodeURIComponent(document.forms[0]["pd_41_ml"].value),
            note_41: encodeURIComponent(document.forms[0]["note_41"].value.slice(0, 5))
        };
        
        // Die Variable jsonString aus der Variable form_data definieren
        var jsonString = JSON.stringify(form_data);
        
        // Die Vadiable jsonString in der Konsole ausgeben
        //console.log(jsonString);
		
		// Verwandeln Sie den JSON-String in ein JavaScript-Objekt
		let jsonObj = JSON.parse(jsonString);

		// Entfernen Sie die unerwünschten Schlüssel
		delete jsonObj['date_saved'];
		delete jsonObj['date'];
		delete jsonObj['url'];
		delete jsonObj['copyright'];
		delete jsonObj['patient_last_name'];
		delete jsonObj['patient_first_name'];
		delete jsonObj['patient_dob'];
		delete jsonObj['input_reevaluation'];
		delete jsonObj['clinician'];

		// Entfernen Sie alle Schlüssel, die mit "note_" beginnen
		for (let key in jsonObj) {
			if (key.startsWith('note_')) {
				delete jsonObj[key];
			}
		}

		// Extrahieren Sie die Werte aus dem bereinigten Objekt in der gleichen Reihenfolge wie die Schlüssel
		let values = Object.values(jsonObj);

		// Konvertieren Sie alle Werte zu Zahlen, addieren Sie 50 und wandeln Sie das Ergebnis in eine Zeichenkette um,
		// füllen Sie einstellige Zahlen mit einer führenden Null auf
		for (let i = 0; i < values.length; i++) {
			let value = Number(values[i]);
			if (!isNaN(value)) {
				let newValue = value + 50;
				values[i] = newValue.toString().padStart(2, '0');
			}
		}

		// Verwandeln Sie die Werte in einen komprimierten String, der mit { beginnt und mit } endet, und entfernen Sie alle Kommas
		let compressedString = 'https://api.periodontalchart-online.com?i=' + values.join('');

		// Das jsonObj und den compressedString ausgeben
		//console.log(jsonObj);
		//console.log(compressedString);
		

		// Loggen Sie die Länge des komprimierten Strings
		//console.log("Die Länge des komprimierten Strings beträgt: " + compressedString.length);
		
        // Die Variable jsonString an die übergeordnete Funktion zurückgeben
        return compressedString;
    }